api = "0.6"

[buildpack]
id = "apppack/python-pdm"
version = "0.0.1"
name = "PDM Buildpack"
keywords = ["python", "pdm"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata]

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/heroku-buildpacks/heroku-nodejs-npm-buildpack"
